# Default parameter values
const DEFAULT_COARSE_K = 2
const DEFAULT_QUANTIZATION_K = 256
const DEFAULT_QUANTIZATION_M = 1
const DEFAULT_QUANTIZATION_METHOD = :pq
const DEFAULT_COARSE_DISTANCE = Distances.SqEuclidean()
const DEFAULT_COARSE_QUANTIZER = :naive  # :naive or :hnsw
const DEFAULT_QUANTIZATION_DISTANCE = Distances.SqEuclidean()
const DEFAULT_COARSE_MAXITER = 25
const DEFAULT_QUANTIZATION_MAXITER = 25
